### ISSUE TITLE
Request Autostart Permission leads to - java.lang.SecurityException: Permission Denial:

### ISSUE THREAD

**Issue by NaoKreuzeder** [RossHS/auto_start_permission#1]
When i request the autostart permission on a mate 20 pro i get this error

![Bildschirmfoto 2024-11-28 um 10 32 53 Kopie](https://github.com/user-attachments/assets/7ab4dd1f-9396-4eaf-8be0-c95858173659)

How to solve this?

**Comment by RossHS** [comment]
Sorry, didn't see the notification. Is the problem still relevant and how to reproduce it?
